# Create CSV with Neighboring Countries

In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
borderbuffer = gpd.read_file('borderbuffer_streets_5km_eunuts.shp')

In [3]:
borderbuffer.head()

,osm_id,highway,oneway,junction,grenze,NUTS_ID,geom_len,index_righ,country1,country2,border,geometry
0,1881629,primary,None,None,0,SE312,2130,57,NO,SE,NOSE,"LINESTRING (4436279.758 4309551.636, 4436323.8..."
1,4361563,primary,None,roundabout,0,SE232,138,57,NO,SE,NOSE,"LINESTRING (4392553.950 3997852.585, 4392558.0..."
2,4361564,motorway,yes,None,0,SE232,188,57,NO,SE,NOSE,"LINESTRING (4392786.782 3998088.796, 4392784.8..."
3,4361565,motorway,yes,None,0,SE232,472,57,NO,SE,NOSE,"LINESTRING (4392777.605 3997901.247, 4392774.7..."
4,4361566,primary,yes,None,0,SE232,86,57,NO,SE,NOSE,"LINESTRING (4392875.400 3998034.102, 4392846.3..."

In [28]:
countries = list(borderbuffer.country1.unique())
countries.extend(list(borderbuffer.country2.unique()))
countries = set(countries)
countries

{'AL',
 'AT',
 'BE',
 'BG',
 'CH',
 'CZ',
 'DE',
 'DK',
 'EE',
 'EL',
 'ES',
 'FI',
 'FR',
 'HR',
 'HU',
 'IE',
 'IT',
 'LI',
 'LT',
 'LU',
 'LV',
 'ME',
 'MK',
 'NL',
 'NO',
 'PL',
 'PT',
 'RO',
 'RS',
 'SE',
 'SI',
 'SK',
 'TR',
 'UK'}

In [26]:
dict_ = {}
for c in countries:
    tab = borderbuffer[(borderbuffer.country1 == c) | (borderbuffer.country2 == c)].copy()
    adj = len(tab.border.unique())
    #dict_.update({c:adj})
    dict_.update({c: {'country':c, 'neighbors': adj}})
df = pd.DataFrame.from_dict(dict_, orient = 'index')

df.to_csv('neighboring_countries.csv')
df

   country  neighbors
AL      AL          3
HU      HU          6
CH      CH          6
BG      BG          5
PT      PT          1
LU      LU          3
LI      LI          2
ME      ME          3
LV      LV          2
ES      ES          2
SI      SI          5
NO      NO          2
EL      EL          4
RO      RO          4
LT      LT          2
IE      IE          1
HR      HR          4
PL      PL          4
CZ      CZ          4
NL      NL          2
DK      DK          1
UK      UK          1
SK      SK          4
MK      MK          4
AT      AT          9
DE      DE          9
SE      SE          2
EE      EE          1
BE      BE          4
RS      RS          7
FI      FI          2
FR      FR          7
TR      TR          2
IT      IT          4